= რატომ უნდა გამოვიყენოთ pip და virtualenv
:hp-alt-title: why use pip and virtualenv

== რა არის pip?
pip არის ხელსაწყო რომელიც აყენებს პითონის ბიბლიოთეკებს რეპოზიტორიდან(https://pypi.python.org[PyPI]). არის უკეთესი ალტერნატივა easy_install -ისა, რომლის გამოყენებაც რეკომენდირებულია და მნიშვნელოვანია პითონის ბიბლიოთეკებთან სამუშაოდ.

pip დასაყენებლად ნებისმიერ ლინუქსის დისტრიბუტივზე შეგვიძლია გავუშვათ ბრძანება easy_install 

 * sudo easy_install -U pip

ასევე შეგვიძლია ჩამოვტვირთოთ კოდის წყარო https://bootstrap.pypa.io/get-pip.py[get-pip.py] ოფიციალური გვერდიდან, შემდეგ ვუშვებთ ბრძანებას

 * sudo python3 get-pip.py # თუ გვინდა python3 ზე დაყენება
 * sudo python2 get-pip.py # თუ გვინდა python2 ზე დაყენება

რის შემდეგ pip დაყენების პროცესი წარმატებით დასრულდა და მისი გამოყენება სრულებით შესაძლებელია.

pip install SomePackage - ბრძანება აყენებს სასურველ ბიბლიოთეკას
pip uninstall SomePackage - ბრძანება შლის სასურველ ბიბლიოთეკას
pip list - ბრძანებით შეგვიძლია ვნახოთ დაყენებული ბიბლიოთეკები

დამატებითი ინფორმაციისთვის წაიკითხეთ https://pip.pypa.io/en/stable/quickstart/[დოკუმენტაცია.- ბმული]

== რა არის virtualenv?
virtualenv არის ხელსაწყო რომელიც ქმნის იზოლირებულ გარემოს პითონისთვის. სადაც შეგვიძლია ჩვენი კოდის ტესტირება სისტემური ბიბლიოთეკების გარეშე. ასევე შეგვიძლია დავამატოთ სხვადასხვა ვერსიები.

დავაყენოთ virtualenv ამისთვის ვიყენებთ pip

 * sudo pip3 install virtualenv  # თუ გვინდა python3 ზე დაყენება
 * sudo pip2 install virtualenv  # თუ გვინდა python2 ზე დაყენება
 
== ვირტუალური გარემოს კონფიგურაცია
შევქმნათ ვირტუალური გარემო

 * virtualenv --python=python3 --no-site-packages pygeo
 
 შექმნის ფოლდერს pygeo სადაც იქნება დაყენებული მოდულები და პითონის გამშვები.
 გამოვიყენოთ ვირტუალური გარემო. ამისთვის ვჭირდება შემდეგი ბრძანებები
 
 * cd pygeo # გადავდივართ ფოლდერში pygeo
 * source bin/activate # ვააქტიურებთ შექმნილ ვირტუალურ გარემოს, რომელის შემდეგ ის იყენებს მხოლოდ pygeo ში არსებულ ან დაყენებულ ბიბლიოთეკებს.
 
შევამოწმოთ pygeo ში არსებული მოდულები(ბიბლიოთეკები) ბრძალებით რომელიც ზემოთ არის მოცემული.

 * pip list
 
   pip (7.1.2)
   setuptools (18.2)
   wheel (0.24.0)

მივიღეთ 3 მოდული რომელსაც ვირტუალური გარემო ქმნის თავისით. 
დავაყენოთ სასურველი ბიბლიოთეკა. მაგ. django

 * pip install django # django პითონის ვებ ფრეიმვორქი.
 
შევამოწმოთ დაყენდა თუ არა django

 * pip list
   Django (1.9.1)
   pip (7.1.2)
   setuptools (18.2)
   wheel (0.24.0)
   
 როგორც ვხედავთ დაყენდა. ასევე შეგვიძლია დავაყენოთ ნებისმიერი ბიბლიოთეკა რომლის გამოყენებაც გვინდა ან გვჭირდება პროექტზე სამუშაოდ. მაგ. pytz, Pillow და ა.შ.
 
  * pip install pytz Pillow
  
 თუ გვსურს რომელიმე ბიბლიოთეკის წაშლა მაგ. django
 
  * pip uninstall django
    .....
    Proceed (y/n)? y # ვეთანხმებით y ჩაწერით რის შემდეგ ბიბლიოთეკა წაიშლება ვირტუალური გარემოდან.
  
  * pip list
	
    pip (7.1.2)
    setuptools (18.2)
    wheel (0.24.0)
    
  დავრწმუნდით რომ django ნამდვილად წაიშლა.
  და ბოლოს ვაკეთებთ ვირტუალური გარემოს დეაქტივაციას
  
  * deactivate # ბრძანებით.
  
დამატებით ინფორმაციისთვის გამოიყენეთ https://virtualenv.pypa.io/en/latest/index.html[დოკუმენტაცია.]