= რატომ უნდა გამოვიყენოთ pip და virtualenv
:hp-alt-title: why use pip and virtualenv

== რა არის pip?
pip არის ხელსაწყო რომელიც აყენებს პითონის ბიბლიოთეკებს რეპოზიტორიდან(https://pypi.python.org[PyPI]). არის უკეთესი ალტერნატივა easy_install -ისა, რომლის გამოყენებაც რეკომენდირებულია და მნიშვნელოვანია პითონის ბიბლიოთეკებთან სამუშაოდ.

pip დასაყენებლად ნებისმიერ ლინუქსის დისტრიბუტივზე შეგვიძლია გავუშვათ ბრძანება easy_install 

 * sudo easy_install -U pip

ასევე შეგვიძლია ჩამოვტვირთოთ კოდის წყარო get-pip.py ოფიციალური გვერდიდან, შემდეგ ვუშვებთ ბრძანებას

 * sudo python3 get-pip.py # თუ გვინდა python3 ზე დაყენება
 * sudo python2 get-pip.py # თუ გვინდა python2 ზე დაყენება

რის შემდეგ pip დაყენების პროცესი წარმატებით დასრულდა და მისი გამოყენება სრულებით შესაძლებელია.

pip install SomePackage - ბრძანება აყენებს სასურველ ბიბლიოთეკას
pip uninstall SomePackage - ბრძანება შლის სასურველ ბიბლიოთეკას
pip list - ბრძანებით შეგვიძლია ვნახოთ დაყენებული ბიბლიოთეკები

დამატებითი ინფორმაციისთვის წაიკითხეთ https://pip.pypa.io/en/stable/quickstart/[დოკუმენტაცია.- ბმული]