= რა არის PyPy?
:hp-alt-title: what is PyPy?

Pypy არის http://speed.pypy.org/[სწრაფი], http://pypy.org/compat.html[თავსებადი] ალტერნატიული განხორციელება http://python.org/[პითონის] ენის (2.7.10 და 3.2.5). მას აქვს რამდენიმე უპირატესობა და გამოკვეთილი თვისებები. არის პითონის ინტერპრეტატორი(თარჯიმანი) და JIT კომპილერი, PyPy აქცენტს აკეთებს სისწრაფეზე, ეფექტურობაზე და თავსებადია ორიგინალ CPython ინტერპრეტატორთან. არის ჩანაცვლება CPython-ის. ის შექმნილია RPython ენის გამოყენებით. ძირითადი მიზეზი გამოიყენოთ PyPy ნაცვლად CPython-ისა არის სისწრაფე(სიჩქარე): ის მუშაობს უფრო სწრაფად ვიდრე CPython.

PyPy ახორციელებს Python 2.7.10 და ეშვება http://en.wikipedia.org/wiki/IA-32[Intel x86 (IA-32)] , http://en.wikipedia.org/wiki/X86_64[x86_64] და http://en.wikipedia.org/wiki/ARM[ARM] პლატფორმებზე. ის მხარს უჭერს ყველა ძირითად ენას, პითონის test suite -ის გავლით (უმნიშვნელო ცვლილება, რომელიც უკვე მიღებულია პითონის ახალ ვერსიებში). ის მხარს უჭერს ყველაზე ხშირად გამოყენებად პითონის სტანდარტული ბიბლიოთეკის მოდულებს. ცნობილია განსხვავებები CPython თან, ნახეთ http://pypy.org/compat.html[თავსებადობის] გვერდზე.

PyPy-ს ასევე აქვს ბეტა რელიზი PyPy3 ზე რომელიც ახორციელებს Python 3.2.5. ის მუშაობს იგივე პლატფორმაზე როგორც ზემოთ არის მოყვანილი.

PyPy ძირითადი თვისებები:

 * სისწრაფე
   ჩვენს http://pypy.org/download.html#with-a-jit-compiler[მთავარ გამშვებს] გააჩნია JIT კომპილერი
   არსებობს ორი შემთხვევა, რომ თქვენ უნდა იცოდეთ, სადაც PyPy ვერ შეძლებს დააჩქაროს თქვენი კოდი:
   * მოკლე გაშვებული პროცესები 
   * თუ სრული დრო იხარჯება ბიბლიოთეკების გაშვებაში (ანუ იგულისხმება C ფუნქციები) და არა რეალურად გაშვებული Python კოდზე,მაშინ JIT კომპილერი ვერ დაგეხმარებათ

პითონის პროგრამები ხშირად ეშვება http://speed.pypy.org/[სწრაფად] PyPy ზე. (http://en.wikipedia.org/wiki/Just-in-time_compilation[რა არის JIT კომპილეერი?])
"თუ თქვენ გსურთ , რომ თქვენი კოდი იყოს სწრაფი, თქვენ უნდა გამოიყენოთ PyPy" - Gudio van Rossum (პითონის შემქმნელი)

 * მეხსიერების გამოყენება

მეხსიერების უკმარისობა პითონზე დაწერილი პროგრამები (ასობით მეგაბაიტს ან მეტს) შეიძლება მოიხმარდნენ, PyPy ცდილობს, რომ რაც შეიძლება ნაკლები მოიხმაროს CPython-თან შედარებით. ეს არ არის ყოველთვის არგუმენტი, რადგან ყველაფერი დეტალებზეა დამოკიდებული. ასევე გაითვალისწინეთ, რომ baseline უფრო მაღალია ვიდრე CPython-ის შემთხვევაში.

თუ თქვენ ხართ დახმარებით დაინტერესებული, ნახეთ http://pypy.org/howtohelp.html[დახმარების] გვერდი.

:hp-tags: PyPy, Compiler[კომპილერი], JIT, python[პითონი]