= პითონის სახელმძღვანელო - აღძრავს თქვენს მადას. ნაწილი 2
:hp-alt-title: Whetting Your Appetite

თუ შენ მუშაობ ბევრს კომპიუტერზე, საბოლოო ჯამში, თქვენ ნახავთ, რომ ზოგიერთი ამოცანა საჭიროებს ავტომატიზაციას. მაგალითად, თქვენ გსურთ შეასრულოთ ძებნა და ჩანაცვლება ძალიან დიდი რაოდენობით ტექსტურ ფაილში ან გადარქმევა და გადალაგება ფოტო ფაილების არის რთული გზა. ალბათ გსურთ დაწეროთ პატარა მოგრებული მონაცემთა ბაზა ან სპეციალიზებული GUI აპლიკაცია ან მარტივი თამაში.

თუ თქვენ ხართ პროფესიონალი პროგრამისტი, თექვენ შეიძლება გქონდეთ ნამუშევარი რამდენიმე ენის C/C++/Java-ს ბიბლიოთეკებში, მაგრამ ჩვევლებრივი ციკლი write/compile/test/re-compile არის ძალიან ნელი. ალბათ თქვენ წერთ ტესტს და ტესტირების კოდი იპოვის რუტინულ ამოცანას. ან შეიძლება გაქვთ დაწერილი პროგრამა, რომელიც შეიძლება გამოიყენოთ გაგრძელება და თქვენ არ გსურთ შეიმუშაონ და განახორციელონ ახალი ენა აპლიკაციისთვის.

პითონი არის მხოლოდ თქვენთვის.

თქვენ შეგიძლიათ დაწეროთ Unix shell სკრიპტები ან Windows bath ფაილები ზოგიერთი ამოცანებისთვის, მაგრამ shell სკრიპტები არიან საუკთესო მარტივად გადასატანი ფაილები და შესაცვლელი ტექსტ მონაცემები, არა განკუთვნილი GUI აპლიკაციებისთვის ან თამაშებისთვის. შეგიძლიათ დაწეროთ C/C++/Java პროგრამა, მაგრამ ის შეიძლება მოითხოვდეს ბევრ დროს განვითარებისთვის(შექმნისთვის) და მიიღებთ პირველ გეგმა პროგრამას. )) პითონი არის მარტივად გამოსაყენებელი, ხელმისაწვდომი WIndows, Mac OS X და Unix ოპერაციულ სისტემებზე, და დაგეხმარებათ მიიღოთ უფრო სწრაფად დასრულებული სამუშაო(პროექტი).

პითონი არის მარტივი გამოსაყენებელი, მაგრამ ეს არის ნამდვილი პროგრამირების ენა, გთავაზობთ უფრო მეტ სტრუქტურას და მხარდაჭერას დიდი პროგრამებისთვის, ვიდრე shell სკრიპტებს ან bath ფაილებს შეუძლია შემოგთავაზოთ. მეორეს მხრივ, პითონი ასევე გთავაზობთ უფრო მეტი შეცდომის შემოწმებას ვიდრე C, და არის ძალიან მაღალი დონის ენა, ჩაშენებული აქვს მაღალი დონის მონაცემთა ტიპები, როგორიცაა მოქნილი მასივები(arrays) და ლექსიკონები(dictionaries). პითონის მოაცემთა ტიპები ბევრად უფრო მოსახერხებელია ვიდრე AWK ან Perl.

პითონი საშუალებას გაძლევთ გაყოთ თქვენი პროგრამა შიდა  მოდულებად, რომელიც შეიძლება გამოიყენოს სხვა პითონის პროგრამებმა. მას გაანია დიდი კოლექცია სტანდარტული მოდულების, რომელიც შეგიძლიათ გამოიყენოთ როგორც საფუძველი თქვენი პროგრამების. ზოგიერთი მოდულები უზრუნველყოფს მსგავს რამეს, როგორიცაა ფაილი I/O, system calls, სოკეტები და კიდევ გრაფიკული ინტერფეისის ხელსაწყოები(GUI toolkits), როგორიცაა Tk.

პითონი არის ინტერპრეტირებული ენა, რომელიც გეხმარებათ თქვენ მნიშვნელოვანი დრო დაუთმოთ პროგრამის განვითარებას, რადგან არ აკეთებს კომპილაციას და დაკავშირება არის საჭირო. ინტერპრეტატორი შეიძლება გამოყენებულ იქნას ინტერაქტიულად. რაც ადვილად ქმნის ექსპერიმენტებს ენაზე, წერს throw-away პროგრამებს, ან შესამოწმებელი ფუნქციების დროს აღმავალი პროგრამების განვითარებას. არის ასევე მოსახერხებელი სამაგიდო კალკულატორი.

პითონი პროგრამებს აძლევს საშუალებას იყოს დაწერილი კომპქატურად და გარკვეულად(კითხვადი სინტაქსი). პითონში დაწერილი პროგრამები, როგორც წესი ბევრად უფრო მოკლეა ვიდრე ექვივალენტი C, C++ ან Java პროგრამები, რამდენიმე მიზეზის გამო:

	* მაღალი დონის მონაცემთა ტიპები საშუალებას გაძლევთ გამოხ	ტოთ რთული ოპერაციები ერთ ხაზიანი ფორმულირებით(single statement).
	* ჯგუფური ფორმულირების დროს წანაცვლების(indentation) ნაცვლად ხდება დაწყებული და დამთავრებული ფრჩხილები.
	* არ არის აუცილებელი ცვლადების ან არგუმენტების დეკლარირება.

პითონის გავრცობა: თუ თქვენ იცით როგორ უნდა პროგრამის შექმნა C-ში ეს არის მარტივი რათა დაამატოთ ახალი ჩაშენებული ფუნქციები ან მოდულის ინტერპრეტატორი, ან შეასრულოს კრიტიკული ოპერაციების მაქსიმალური სიჩქარე, ან დაუკავშიროთ პითონის პროგრამები ბიბლიოთეკებს, რომ შეიძლება ხელმისაწვდომი იყოს მხოლოდ ორობითი(binary) ფორმით(როგორიცაა vendor-specific გრაფიკული ბიბლიოთეკა). შენ შეგიძლია დაუკავშირო პითონის ინტერპრეტატორში C-ში დაწერილი აპლიკაცია და გამოიყენო ის როგორც გაგრძელება ან ენის ბრძანება აპლიკაციისთვის.

სხვათა შორის, ენის სახელი არის BBC გადაცემა “Monty Python’s Flying Circus”-დან და არაფერი აკავშირებს ქვეწარმავლებთან.

ახლა თქვენ ხართ აღფრთოვანებული პითონის შესახებ, თქვენს გსურთ გამოცადოთ ის კიდევ რამდენიმე დეტალში. ტუტორიალების კითხვისას და ყურებისას თქვენ მხოლოდ სიმულიაციას ახდენთ. ენის შესწავლის საუკეთესო საშუალება მისი პრაქტიკაში გამოყენებაა.

:hp-tags: docs[დოკუმენტაცია],python[პითონი],tutorial[გაკვეთილი]