= პითონი დამწყებთათვის

== პითონი დამწყებთათვის
გამარჯობა! ხართ თუ არა სრულიად ახალი პროგრამირებაში? თუ არა მაშინ მიგვაჩნია რომ, თქვენ უნდა ეძებდეთ ინფორმაციას, რატომ და როგორ უნდა დავიწყოთ პითონის სწავლა. საბედნიეროდ გამოცდილ პროგრამისტს ნებისმიერ პროგრამირების ენაში(რომელიც არ უნდა იყოს ის) შეუძლია გაუშვას ძალიან სწრაფად. ასევე ადვილია დამწყებთათვის მისი გამოყენება და სწავლა. მიყევით ბმულს

== ინსტალაცია(დაყენება)

პითონის ინსტალაცია ზოგადად არის ძალიან ადვილი და დღეისთვის ბევრი ლინუქსის და იუნიქსის დისტრიბუტივები მოიცავს პითონის ბოლო ვერსიას. თუ თქვენ უნდა დააყენოთ პითონი და არ ხართ დარწმუნებული, რომ შეძლებთ, შგიძლიათ ნახოთ BeginnersGuide/Download ვიკი გვერდი.

== სწავლა

სანამ დაიწყებთ, შეგიძლიათ გაარკვიოთ რომელი IDE და text editor ები არის მორგებული რათა შეძლოთ პითონის მარტივად რედაქტირება. დაათვალიერეთ გაცნობითი ხასიათის წიგნები ან გადახედეთ კოდის ნიმუშებს, რომელიც შეიძლება სასარგებლო გამოდგეს თქვენთვის.

არსებობს გაკვეთილები, რომელიც განკუთვნილია გამოცდილი პროგრამისტებისთვის BeginnersGuide/Tutorials. არსებობს ასევე რესურსები სხვა ენებზე, რომელიც შეიძლება გამოგადგეთ თუ ინგლისური არ არის თქვენი პირველი ენა.

ონლაინ დოკუმენტაცია არის თქვენი პირველი წყარო საბოლოო ინფორმაციის მისაღებად. არსებობს საკმაოდ მოკლე გაკვეთილი, რომელიც გაძლევთ ძირითად ინფორმაციას ენის შეასახებ. თქვენ შეგიძლიათ მიყვეთ library reference-ს სრული აღწერისთვის პითონის ბევრი ბიბლიოთეკების და language reference-ს პითონის სინტაქსის სრული განმარტების მისაღებად. თუ თქვენ ეძებთ პითონის სკრიპტებს და ნიმუშებს შეგიძლიათ დაათვალიეროთ ActiveState Python Cookbook

== ვეძებთ რაიმე კონკრეტულს?


:hp-tags: python[პითონი]