= პითონი დამწყებთათვის
:hp-alt-title: Python For Beginners

== პითონი დამწყებთათვის

გამარჯობა! ხართ თუ არა http://wiki.python.org/moin/BeginnersGuide/NonProgrammers[სრულიად ახალი პროგრამირებაში]? თუ არა მაშინ მიგვაჩნია რომ, თქვენ უნდა ეძებდეთ ინფორმაციას, რატომ და როგორ უნდა დავიწყოთ პითონის სწავლა. საბედნიეროდ გამოცდილ პროგრამისტს ნებისმიერ პროგრამირების ენაში(რომელიც არ უნდა იყოს ის) შეუძლია გაუშვას ძალიან სწრაფად. ასევე ადვილია დამწყებთათვის მისი გამოყენება და სწავლა. http://wiki.python.org/moin/BeginnersGuide/NonProgrammers[მიყევით ბმულს]

== ინსტალაცია(დაყენება)

პითონის ინსტალაცია ზოგადად არის ძალიან ადვილი და დღეისთვის ბევრი ლინუქსის და იუნიქსის დისტრიბუტივები მოიცავს პითონის ბოლო ვერსიას. თუ თქვენ უნდა დააყენოთ პითონი და არ ხართ დარწმუნებული, რომ შეძლებთ, შგიძლიათ ნახოთ http://wiki.python.org/moin/BeginnersGuide/Download[BeginnersGuide/Download] ვიკი გვერდი.

== სწავლა

სანამ დაიწყებთ, შეგიძლიათ გაარკვიოთ რომელი http://wiki.python.org/moin/IntegratedDevelopmentEnvironments[IDE] და http://wiki.python.org/moin/PythonEditors[text editor] ები არის მორგებული რათა შეძლოთ პითონის მარტივად რედაქტირება. დაათვალიერეთ http://wiki.python.org/moin/IntroductoryBooks[გაცნობითი ხასიათის წიგნები] ან გადახედეთ http://wiki.python.org/moin/BeginnersGuide/Examples[კოდის ნიმუშებს], რომელიც შეიძლება სასარგებლო გამოდგეს თქვენთვის.

არსებობს გაკვეთილები, რომელიც განკუთვნილია გამოცდილი პროგრამისტებისთვის http://wiki.python.org/moin/BeginnersGuide/Programmers[BeginnersGuide/Tutorials]. არსებობს ასევე https://www.python.org/doc/nonenglish/[რესურსები სხვა ენებზე], რომელიც შეიძლება გამოგადგეთ თუ ინგლისური არ არის თქვენი პირველი ენა.

http://docs.python.org/[ონლაინ დოკუმენტაცია] არის თქვენი პირველი წყარო საბოლოო ინფორმაციის მისაღებად. არსებობს საკმაოდ მოკლე http://docs.python.org/3/tutorial/[გაკვეთილი], რომელიც გაძლევთ ძირითად ინფორმაციას ენის შეასახებ. თქვენ შეგიძლიათ მიყვეთ http://docs.python.org/3/library/[library reference]-ს სრული აღწერისთვის პითონის ბევრი ბიბლიოთეკების და http://docs.python.org/3/reference/[language reference]-ს პითონის სინტაქსის სრული განმარტების მისაღებად. თუ თქვენ ეძებთ პითონის სკრიპტებს და ნიმუშებს შეგიძლიათ დაათვალიეროთ http://code.activestate.com/recipes/langs/python/[ActiveState Python Cookbook]

== ეძებთ რაიმე კონკრეტულს?

თუ თქვენ გსურთ რამე კონკრეტული პროგრამა ან ბიბლიოთეკა ხელმისაწვდომია თუ არა პითონზე არსებობს მთელი რიგი შესაძლო წყაროებზე ინფორმაცია. პითონის ვებ საიტი უზრუნველყოფს http://pypi.python.org/pypi?%3Aaction=index[PyPI(Python Package Index)]. არსებობს ასევე https://www.python.org/search[საძიებო გვერდი] სადაც არის მთელი რიგი წყაროების პითოთნათ დაკავშირებული ინფორმაციების. წინააღმდეგ შემთხვევაში, უბრალოდ მიმართეთ http://www.google.com/[Google]-ს და საძიებო სტრიქონში გამოიყენეთ სიტყვა "python" ამ გზით თქვენ შეიძლება მიიღოთ სასურველი შედეგი. თუ ყველა ეს გზა წარუმატებელი გამოდგა, თქვენ შეგიძლიათ იკითხოთ პითონის news:comp.lang.python[სიახლეების ჯგუფში] და ეს არის კარგი შანსი, რომ თქვენ დაგაყენონ სწორ გზაზე.

== ხშირად დასმული კითხვები(FAQ)

თუ თქვენ გაქვთ კითხვა, ეს არის კარგი იდეა, რომ ნახოთ http://docs.python.org/3/faq/["ხშირად დასმული კითხვები"], რომელიც პასუხობს დასმულ შეკითხვებს პითონის შესახებ.


:hp-tags: python[პითონი]